_Dockerized/mldashboard/web/project/algorithms/views.py
from flask import render_template, redirect, url_for, Blueprint, session

## BLUEPRINT INIT

algorithms_blueprint = Blueprint(
    'algorithms', __name__,
    template_folder="templates"
)

from .ml_algorithms import *


## User Login
@algorithms_blueprint.context_processor
def context_processor():
    current_user = session.get('current_user') or 'Guest'
    return dict(current_user=current_user)


#################################################################### ML ESTIMATOR TYPES SUMMARY #####################################################################################################################


## ML TYPE CHOICE HANDLING ##########################################################     

@algorithms_blueprint.route('/summary/<type_id>')
def summary(type_id):
    if type_id == "Regression":
        return redirect(url_for("algorithms.regression"))
    elif type_id == "Classification":
        return redirect(url_for("algorithms.classification"))
    else:
        return redirect(url_for("algorithms.clustering"))


## REGRESSION INITIATION ############################################################

@algorithms_blueprint.route('/regression')
def regression():
    ## Decribe ml type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Regression")

    ## Describe dataset
    dataset, X, y, describe, rows, columns = regression_dataset()

    single_prediction = ''

    return render_template('regression.html', data=dataset.to_html(),
                           describe=describe.to_html(), single_prediction=single_prediction, rows=rows,
                           columns=columns, algorithm_preprocessors=algorithm_preprocessors,
                           algorithm_issues=algorithm_issues)


## REGRESSION ALGORITHM CHOICE HANDLING #############################################

@algorithms_blueprint.route('/regressor/<regressor_id>')
def regressor(regressor_id):
    choice = regressor_id

    ## Describe ML type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Regression")

    ## Describe dataset
    dataset, X, y, describe, rows, columns = regression_dataset()

    ## Apply Chosen Algrotihm
    if choice == 'polynomial_regression':
        X_grid, plot_prediction, single_prediction = polynomial_regression(X, y)
    elif choice == 'svr':
        X_grid, plot_prediction, single_prediction = svr(X, y)
    else:
        X_grid, plot_prediction, single_prediction = randomforest(X, y)

    ## Visualize Dataset
    regression_plot(choice, X, y, X_grid, plot_prediction)

    return render_template('regression.html', data=dataset.to_html(),
                           describe=describe.to_html(), single_prediction=single_prediction, choice=choice,
                           rows=rows, columns=columns, algorithm_preprocessors=algorithm_preprocessors,
                           algorithm_issues=algorithm_issues,
                           )


## CLASSIFICATION INITIATION ########################################################

@algorithms_blueprint.route('/classification')
def classification():
    ## Decribe ml type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Classification")

    ## Describe dataset
    dataset, X, y, describe, rows, columns, dataset_head = classification_dataset()

    single_prediction = ''

    return render_template('classification.html', data=dataset_head.to_html(),
                           describe=describe.to_html(), single_prediction=single_prediction,
                           rows=rows, columns=columns, algorithm_preprocessors=algorithm_preprocessors,
                           algorithm_issues=algorithm_issues)


## CLASSIFICATION ALGORITHM CHOICE HANDLING #########################################

@algorithms_blueprint.route('/classifier/<classifier_id>')
def classifier(classifier_id):
    ## Decribe ml type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Classification")

    ## Describe dataset
    dataset, X, y, describe, rows, columns, dataset_head = classification_dataset()

    # Splitting the dataset into the Training set and Test set
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

    # Feature Scaling
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)

    # Choose classifier to fit the Training set
    classifier = GaussianNB() if classifier_id == 'naive_bayes' \
        else KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2) if classifier_id == 'k-nearest_neighbors' \
        else SVC(kernel='rbf', random_state=0)
    classifier.fit(X_train, y_train)

    # Predicting the Test set results
    y_pred = classifier.predict(X_test)

    # Making the Confusion Matrix
    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y_test, y_pred)
    df = pd.DataFrame(cm, index=['Bought: Yes', 'Bought: No'], columns=['Predicted: Yes', 'Predicted: No'])
    accuracy = (df.iloc[0, 0] + df.iloc[1, 1])
    accuracy = "{}%".format(float(accuracy))

    # Visualising the Test set results with the heatmap
    classification_plot(classifier_id, X_test, y_test, classifier)

    return render_template('classification.html', data=dataset_head.to_html(),
                           describe=describe.to_html(), cma=df.to_html(),
                           rows=rows, columns=columns, acc=accuracy, classifier_id=classifier_id,
                           algorithm_preprocessors=algorithm_preprocessors,
                           algorithm_issues=algorithm_issues)


## CLUSTERING INITIATION ############################################################

@algorithms_blueprint.route('/clustering')
def clustering():
    ## Decribe ml type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Clustering")

    ## Describe dataset
    dataset, X, describe, rows, columns, dataset_head = clustering_dataset()

    return render_template('clustering.html', data=dataset_head.to_html(),
                           describe=describe.to_html(), rows=rows, columns=columns,
                           algorithm_preprocessors=algorithm_preprocessors, algorithm_issues=algorithm_issues)


## CLUSTERING ALGORITHM CHOICE HANDLING #############################################  

@algorithms_blueprint.route('/clusterer/<clusterer_id>')
def clusterer(clusterer_id):
    ## Decribe ml type
    algorithm_preprocessors, algorithm_issues = algorithm_characteristics("Clustering")

    ## Describe dataset
    dataset, X, describe, rows, columns, dataset_head = clustering_dataset()

    choice = clusterer_id

    if choice == 'hierarchical_clustering':
        ## Using the dendogram to find the optimal number of clusters
        dendrogram_plot(choice, X)
        ## Result = 5

        ## Fitting Hierarchical Clustering to the dataset (optimal clusters = 5)
        hc = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
        y_pred = hc.fit_predict(X)

        ## Visualising the clusters 

    if choice == 'k-means_clustering':

        ## Using the elbow method to find the optimal number of clusters
        wcss = []  ## initialize the list
        for i in range(1, 11):
            kmeans = KMeans(n_clusters=i,  ## from 1 to 10
                            init='k-means++',  ## k-means++ to avoid random initialziation trap
                            max_iter=300,  ## 300 is deafault
                            n_init=10,  ## algorithm runs with different initial centroids
                            random_state=0)
            kmeans.fit(X)
            wcss.append(kmeans.inertia_)  ## to compute wcss
        ## Result = 5    

        ## Visualising Elbow Method
        elbow_plot(choice, wcss)

        ## Applying k-means to the mall dataset - from the plot we can see that optimum is 5 clusters.
        kmeans = KMeans(n_clusters=5,
                        init='k-means++',  ## k-means++ to avoid random initialziation trap
                        max_iter=300,  ## 300 is deafault
                        n_init=10,  ## algorithm runs with different initial centroids
                        random_state=0)
        y_pred = kmeans.fit_predict(X)  ## fit_predict returns a cluster for each observation

    ## Visualising the clusters
    clustering_plot(choice, X, y_pred)

    return render_template('clustering.html', data=dataset_head.to_html(),
                           describe=describe.to_html(), rows=rows, columns=columns,
                           choice=choice, algorithm_preprocessors=algorithm_preprocessors,
                           algorithm_issues=algorithm_issues)

_Dockerized/mldashboard/web/project/algorithms/templates/classification.html
{% extends 'base.html' %} {% block content %}
<div class="card text-center" id="main_card">
    <h1>Machine Learning: Classification</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <div class="row text-center">
                    <div class="col-md-3 text-left" id="text_card">
                        <h2>Overview:</h2>
                        <p>Classification identifies to which of a set of categories a new observation belongs. Classification problem is an example of pattern recognition that predict a  
                        probability of a given example belonging to each output class. The output variables are often called labels or categories.
                        </p>
                    </div>
                    <div class="col-md-3 text-left" id="text_card">

                        <h2>Real life example:</h2>
                        <li>Email spam detector</li>
                        <li>Handwritten Digit Recognition.</li>
                        <li>Speech Recognition.</li>
                        <li>DNA Sequence Classification.</li>
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Preprocessing:</h2>
                        {% for element in algorithm_preprocessors %}
                        <li> {{element}} </li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Possible issues:</h2>
                        {% for element in algorithm_issues %}
                        <li>{{element}}</li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Read more:</h2>
                        <li><a target="_blank" href="https://machinelearningmastery.com/classification-versus-regression-in-machine-learning/">Machine Learning Mastery</a></li>
                        <li><a target="_blank" href="https://www.geeksforgeeks.org/regression-classification-supervised-machine-learning/">GeeksforGeeks</a></li>
                        <li><a target="_blank" href="https://www.youtube.com/watch?v=f7YB73F0zDo">ML Introduction: Classification</a></li>
                        <li><a target="_blank" href="https://www.datascience.com/blog/regression-and-classification-machine-learning-algorithms">Regression vs. Classification</a></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row"></div>
    <h1>ML Regression in Action</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-4 text-left">
            <div class="card" id="description_card">
                <h2>Description:</h2>
                <br>
                <h4>No. of Rows: {{rows}}</h4>
                <h4>No. of Columns: {{columns}}</h4>

            </div>
            <br>
            <div class="card" id="description_card">
                <h2>Statistical Data:</h2>

                <br> <br>{{describe | safe}}
                <br>
                <ol></ol>
            </div>
        </div>
        <div class="col-md-8 text-left">

            <div class="card" id="description_card">
                <h2 style="margin-left:0px">Business Case:</h2>
                <h1></h1>
                <p>We are Social Network Data Science Department. One of our clients is a luxury watch company that has just launched brand new line of a products. We have been approached with a question if we can predict 
                which characteristics can determine if social network user will be more likely to buy a new product. Our model will be based on dataset which contains user characteristics. Last column contains information if user bought product (1) or not (0). 
                </p>

            </div>
            <br>
            <div class="card" id="description_card">
                <h2>Dataset Head:</h2>
                <br> {{data | safe}}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <h2>Data Question:</h2>
                <p>"Based on Age and Estimated Salary, can we predict if user would buy a watch?"</p>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 text-center">
            <div class="card" id="algorithm">
                <h2>Choose Algorithm:</h2>
                <br>
                <br>
                 <br>
                <a href="{{url_for('algorithms.classifier', classifier_id='k-nearest_neighbors')}}" class="waves-effect waves-light btn-large" id="navigation">K-Nearest Neighbors</a>
                <br>
                 <br>
                <a href="{{url_for('algorithms.classifier', classifier_id='kernel_svm')}}" class="waves-effect waves-light btn-large" id="navigation">Kernel SVM</a>
                <br>
                 <br>
                <a href="{{url_for('algorithms.classifier', classifier_id='naive_bayes')}}" class="waves-effect waves-light btn-large" id="navigation">Naive Bayes</a>
                <br>
                <ol></ol>
            </div>

        </div>
        <div class="col-md-6 text-center">
            <div class="card" id="pyplot">
                <h2>Visualisation:</h2>
                <img src="{{url_for('static', filename='img/{}.svg'.format(classifier_id))}}" id="plot" alt="plot">
            </div>

        </div>
        <div class="col-md-3 text-left">
            <div class="card" id="algorithm">
                <h2>Confusion Matrix:</h2>
                <br> <br> {{cma | safe}}
                <br> <br> 
                <h2 style="display:inline">Algorithm Accuracy:</h2>

                <p style="display:inline; margin-left:-12px;" id="accuracy">{{ acc }}</p>
            </div>
        </div>
    </div>

</div>

</div>

{% endblock %}

_Dockerized/mldashboard/web/project/algorithms/templates/clustering.html
{% extends 'base.html' %} {% block content %}
<div class="card text-center" id="main_card">
    <h1>Machine Learning: Clustering</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <div class="row text-center">
                    <div class="col-md-3 text-left" id="text_card">
                        <h2>Overview:</h2>
                        <p>Clustering is a main task of exploratory data mining that involves dividing the population or data points with similar characteristics and assigning them into clusters. Clustering is a unsupervised learning method and is a common
                            technique for statistical data analysis. The output of the algorithm would be a set of “labels” assigning each point to one of the clusters.

                        </p>
                    </div>
                    <div class="col-md-3 text-left" id="text_card">

                        <h2>Real life example:</h2>
                        <li>Identifying groups of houses according to their characteristics.</li>
                        <li>Classification of plants and animals given their features.</li>
                        <li>Customer segmentation.</li>
                        <li>Classify the crimes based on age groups.</li>
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Preprocessing:</h2>
                        {% for element in algorithm_preprocessors %}
                        <li> {{element}} </li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Possible issues:</h2>
                        {% for element in algorithm_issues %}
                        <li>{{element}}</li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Read more:</h2>
                        <li><a target="_blank" href="https://medium.com/machine-learning-bites/machine-learning-unsupervised-learning-clustering-d686af2466e1">ML: Clustering</a></li>
                        <li><a target="_blank" href="https://www.analyticsvidhya.com/blog/2016/11/an-introduction-to-clustering-and-different-methods-of-clustering/">An Introduction to Clustering</a></li>
                        <li><a target="_blank" href="https://towardsdatascience.com/the-5-clustering-algorithms-data-scientists-need-to-know-a36d136ef68">Towards Data Science</a></li>
                        <li><a target="_blank" href="https://www.geeksforgeeks.org/clustering-in-machine-learning/">Clustering in Machine Learning</a></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row"></div>
    <h1>ML Regression in Action</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-4 text-left">
            <div class="card" id="description_card">
                <h2>Description:</h2>
                <br>
                <h4>No. of Rows: {{rows}}</h4>
                <h4>No. of Columns: {{columns}}</h4>

            </div>
            <br>
            <div class="card" id="description_card">
                <h2>Statistical Data:</h2>
                <br> <br>{{describe | safe}}
                <br>
                <ol></ol>
            </div>
        </div>
        <div class="col-md-8 text-left">

            <div class="card" id="description_card">
                <h2 style="margin-left:0px">Business Case:</h2>
                <h1></h1>
                <p>One of the biggest shopping malls in the city collects information about their membership card subscribers. Database contains various columns like age, gender or annual income. Last column in a database is a spending score, computed for
                    each client based on several criteria like money spent or weekly visits. We have been hired to segment mall clients into groups based on their annual income and spending score. We have to determine how many groups there would be and
                    label them.
                </p>

            </div>
            <br>
            <div class="card" id="description_card">
                <h2>Dataset Head:</h2>
                <br> {{data | safe}}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <h2>Data Question:</h2>
                <p>Can we group subscribers the way that will help mall management readjust their advertisement strategy?</p>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 text-center">
            <div class="card" id="algorithm">
                <h2>Choose Algorithm:</h2>
                <br>
                <br>
                 <br>
                <a href="{{url_for('algorithms.clusterer', clusterer_id='k-means_clustering')}}" class="waves-effect waves-light btn-large" id="navigation">K-Means Clustering</a>
                <br>
                 <br>
                <a href="{{url_for('algorithms.clusterer', clusterer_id='hierarchical_clustering')}}" class="waves-effect waves-light btn-large" id="navigation">Hierarchical Clusters</a>
                <br>
                <ol></ol>
            </div>

        </div>
        <div class="col-md-3 text-center">
            <div class="card" id="pyplot">
                <h2>Determining number of clusters:</h2>
                <img src="{{url_for('static', filename='img/{}-determine.svg'.format(choice))}}" id="plot-determine" alt="plot">
            </div>
        </div>
        <div class="col-md-6 text-center">
            <div class="card" id="pyplot">
                <h2>Visualisation:</h2>
                <img src="{{url_for('static', filename='img/{}.svg'.format(choice))}}" id="plot" alt="plot">
            </div>
        </div>
    </div>

</div>

</div>

{% endblock %}

_Dockerized/mldashboard/web/project/algorithms/templates/regression.html
{% extends 'base.html' %} {% block content %}
<div class="card text-center" id="main_card">
    <h1>Machine Learning: Regression</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <div class="row text-center">
                    <div class="col-md-3 text-left" id="text_card">
                        <h2>Overview:</h2>
                        <p>Regression is a basic and commonly used type of predictive analysis. It investigates the relationship between a dependent and independent variable. Regression problem requires the prediction of a quantity, such as amounts and
                            sizes. An output variable is a real-value - an integer or floating point value.
                        </p>
                    </div>
                    <div class="col-md-3 text-left" id="text_card">

                        <h2>Real life example:</h2>
                        <li>Examine last month's customer service calls drop.</li>
                        <li>Predict monthly gift card sales.</li>
                        <li>Predict potential clients who might default.</li>
                        <li>Describe impact of product price on number of sales.</li>
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Preprocessing:</h2>
                        {% for element in algorithm_preprocessors %}
                        <li> {{element}} </li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Possible issues:</h2>
                        {% for element in algorithm_issues %}
                        <li>{{element}}</li>
                        {% endfor %}
                    </div>
                    <div class="col-md-2 text-left" id="text_card">
                        <h2>Read more:</h2>
                        <li><a target="_blank" href="https://machinelearningmastery.com/classification-versus-regression-in-machine-learning/">Machine Learning Mastery</a></li>
                        <li><a target="_blank" href="https://www.geeksforgeeks.org/regression-classification-supervised-machine-learning/">GeeksforGeeks</a></li>
                        <li><a target="_blank" href="https://www.youtube.com/watch?v=f7YB73F0zDo">ML Introduction: Regression</a></li>
                        <li><a target="_blank" href="https://towardsdatascience.com/selecting-the-best-machine-learning-algorithm-for-your-regression-problem-20c330bad4ef">Towards Data Science</a></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row"></div>
    <h1>ML Regression in Action</h1>
    <div class="row"></div>
    <div class="row">
        <div class="col-md-4 text-left">
            <div class="card" id="description_card">
                <h2>Description:</h2>
                <br>
                <h4>No. of Rows: {{rows}}</h4>
                <h4>No. of Columns: {{columns}}</h4>

            </div>    
            <br>
            <div class="card" id="description_card">    
                <h2>Statistical Data:</h2>
            
                <br> <br>{{describe | safe}}
                <br> <ol></ol>
            </div>
        </div>
        <div class="col-md-8 text-left">
            
                <div class="card" id="description_card">
                    <h2 style="margin-left:0px">Business Case:</h2>
                    <h1></h1>
                    <p>HR team are about to hire a new employee and they are about to make a salary offer. New employee has over 20 years of experience and he claims that his previous salary was 160K/annum. Before making final offer HR decided to check candidate
                        story. All the info that we manage to get is the salary brackets for different levels and that our candidate <br>was half-way between level 6 & 7:
                    </p>

                </div>
                <br>
                <div class="card" id="description_card">
                    <h2>Dataset:</h2>
                    <br> {{data | safe}}
                </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 text-center" id="desc_col">
            <div class="card" id="description_card">
                <h2>Data Question:</h2>
                <p>"Based on gathered data, can we estimate what was a salary of our candidate in a previous job?"</p>
               
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 text-center">
            <div class="card" id="algorithm">
                <h2>Choose Algorithm:</h2>
                <br>
                <br>
                 <br>
                <a href="{{url_for('algorithms.regressor', regressor_id='polynomial_regression')}}" class="waves-effect waves-light btn-large" id="navigation">Polynomial Regression</a>
                <br>
                 <br>
                <a href="{{url_for('algorithms.regressor', regressor_id='svr')}}" class="waves-effect waves-light btn-large" id="navigation">SVR</a>
                <br>
                 <br>
                <a href="{{url_for('algorithms.regressor', regressor_id='randomforest')}}" class="waves-effect waves-light btn-large" id="navigation">Randomforest</a>
                <br>
                <ol></ol>
            </div>

        </div>
        <div class="col-md-6 text-center">
            <div class="card" id="pyplot">
                <h2>Visualisation: </h2>
                <img src="{{url_for('static', filename='img/{}.svg'.format(choice))}}" id="plot" alt="plot">
            </div>

        </div>
        <div class="col-md-3 text-left">
            <div class="card" id="algorithm">
                <h2>Salary Estimation:</h2>
                <br>
                    <p style="display:inline; margin-left:-12px;">Estimated salary was:</p><h2 style="display:inline">{{ single_prediction }}<h2>
                </div>
            </div>
        </div>

    </div>
    
</div>

{% endblock %}

_Dockerized/mldashboard/web/project/algorithms/templates/summary.html
{% extends 'base.html' %} {% block content %}
<div id="page-wrapper">
            <div id="page-algorithm">
                <div class="dashboard-cards">
                    <div class="row"></div>
                    <div class="row"></div>
                    <div class="row">
                        <div class="col-xs-2 col-sm-2 col-md-0 col-lg-1"></div>
                        <div class="col-md-12 col-lg-10 text-center">
                            <div class="card" id="info_content">

                                <h2></h2>

                            </div>
                        </div>

                        <div class="col-xs-2 col-sm-2 col-md-0 col-lg-1"></div>
                        <div class="row"></div>
                    </div>
                    <div class="row" id="menu_row">
                        <div class="col-xs-0 col-sm-0 col-md-0 col-lg-1"></div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 text-center">
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                                    <div class="card" id="info_content">
                                        <h2>Preprocessing</h2>
                                        <div class="card-panel">
                                            <p>Label Encoding</p>
                                        </div>
                                        <div class="card-panel">
                                            <p>One Hot Encoding</p>
                                        </div>
                                        <div class="card-panel">
                                            <p>StandardScaler</p>
                                        </div>
                                        <div class="card-panel">
                                            <p>Train-Test Split</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-3 text-center">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <div class="card" id="info_content">
                                        <h2>Parameters</h2>
                                        <div class="card-panel">
                                            <p>train_test_split(test_size)</p>
                                        </div>
                                        <div class="card-panel">
                                            <p>SVR(kernel)</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <div class="card" id="info_content">
                                        <h2>Red Flags</h2>
                                        <div class="card-panel" id="red_flag">
                                            <p>Dummy Variable Trap</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                            </div>
                        </div>
                        
        </div>
        
{% endblock %}