_Dockerized/mldashboard/web/project/library/views.py
from flask import render_template, redirect, url_for, send_file, session, request, Blueprint
from io import BytesIO

## Blueprint Init

library_blueprint = Blueprint(
    'library', __name__,
    template_folder="templates"
)

from .models import *
from project.algorithms.models import *

## Define file upload allowed extensions

ALLOWED_EXTENSIONS = set(['py'])


########################################################################## MAIN DASHBOARD ###################################################################################################################    


## MAIN DASHBOARD - "LIBRARY" #######################################################

@library_blueprint.route('/')
def library():
    codes = CodeRepo.query.all()
    types = TypeModel.query.all()
    current_user = session.get('current_user') or 'Guest'

    return render_template("library.html", codes=codes, types=types
                           , current_user=current_user)


## DOWNLOAD TEMPLATE ################################################################

@library_blueprint.route('/download_code/<code_id>', methods=['GET'])
def download_code(code_id):
    the_code = CodeRepo.query.filter_by(id=code_id).first()
    click = the_code.downloads + 1  ## downloads counter
    the_code.downloads = click
    db.session.commit()

    return send_file(BytesIO(the_code.file),
                     attachment_filename='{}.py'.format(the_code.name),  ## return file
                     as_attachment=True)


## INITIATE TEMPLATE UPLOAD ######################################################### 

@library_blueprint.route('/add_request')
def add_request():
    types = TypeModel.query.all()
    complexities = ComplexityModel.query.all()
    methods = MethodModel.query.all()
    current_user = session.get('current_user') or 'Guest'

    return render_template('add_request.html', types=types, complexities=complexities,
                           methods=methods, current_user=current_user)


## DEFINE ALLOWED TEMPLATE FILE FORMAT ##############################################   

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


## UPLOAD NEW TEMPLATE HANDLING #####################################################   

@library_blueprint.route('/new_code', methods=['POST'])
def new_code():
    codes = CodeRepo.query.all()
    current_user = session.get('current_user') or 'Guest'

    ## Exceptions handling:

    if not 'inputFile' in request.files:
        return render_template('error.html', current_user=current_user)

    if not 'type_of_algorithm' in request.form or not 'complexity' in request.form:
        return render_template('error.html', current_user=current_user)
    if not 'method' in request.form:
        return render_template('error.html', current_user=current_user)
    if request.form['name'] == '' or request.form['author'] == '':
        return render_template('error.html', current_user=current_user)

    ## All good
    else:
        code_file = request.files['inputFile']  ## check file format
        if code_file and allowed_file(code_file.filename):
            code_file = code_file.read()
        else:
            return render_template('error.html', current_user=current_user)

        code = CodeRepo(name=request.form['name'],
                        type_of_algorithm=request.form['type_of_algorithm'],
                        complexity=request.form['complexity'],
                        method=request.form['method'],
                        author=request.form['author'],
                        file=code_file,
                        downloads=0)
        db.session.add(code)
        db.session.commit()
        return redirect(url_for("library.library"))


## EDITING TEMPLATE INITIATION ######################################################

@library_blueprint.route('/edit_code/<code_id>')
def edit_code(code_id):
    the_code = CodeRepo.query.filter_by(id=code_id).first()
    types = TypeModel.query.all()
    complexities = ComplexityModel.query.all()
    methods = MethodModel.query.all()
    current_user = session.get('current_user') or 'Guest'

    return render_template('edit_code.html', code=the_code, types=types,
                           complexities=complexities, methods=methods,
                           current_user=current_user)


## UPDATE TEMPLATE HANDLING #########################################################

@library_blueprint.route('/update_code/<code_id>', methods=["POST"])
def update_code(code_id):
    current_user = session.get('current_user') or 'Guest'
    the_code = CodeRepo.query.filter_by(id=code_id).first()

    the_code.name = request.form['name']
    the_code.type_of_algorithm = request.form['type_of_algorithm']
    the_code.complexity = request.form['complexity']
    the_code.method = request.form['method']
    the_code.author = request.form['author']

    ## Exceptions

    if request.form['name'] == '' or request.form['author'] == '':
        return render_template('error.html', current_user=current_user)
    if 'inputFile' in request.files:
        code_file = request.files['inputFile']
        if code_file and allowed_file(code_file.filename):
            code_file = code_file.read()
            the_code.file = code_file
            db.session.commit()
            return redirect(url_for("library.library"))
        else:
            return render_template('error.html', current_user=current_user)

    ## All good

    else:
        db.session.commit()
        return redirect(url_for("library.library"))


## DELETE TEMPLATE HANDLING #########################################################    

@library_blueprint.route('/delete_code/<code_id>')
def delete_code(code_id):
    the_code = CodeRepo.query.filter_by(id=code_id).first()
    db.session.delete(the_code)
    db.session.commit()
    return redirect(url_for("library.library"))


## MANAGE DB VIEWS #################################################################


@library_blueprint.route('/manage_db')
def manage_db():
    current_user = session.get('current_user') or 'Guest'

    types = AlgorithmModel.query.all()

    return render_template('manage_db.html', current_user=current_user, types=types)


@library_blueprint.route('/add_algorithm_type', methods=['POST'])
def add_algorithm_type():
    algo_type = request.form['type']
    new_type = TypeModel(type_of_algorithm=algo_type)
    new_type.save_to_db()
    return redirect(url_for("library.manage_db"))


@library_blueprint.route('/add_complexity', methods=['POST'])
def add_complexity():
    complexity = request.form['complexity']
    new_complexity = ComplexityModel(complexity=complexity)
    new_complexity.save_to_db()
    return redirect(url_for("library.manage_db"))


@library_blueprint.route('/add_method', methods=['POST'])
def add_method():
    method = request.form['method']
    new_method = MethodModel(method=method)
    new_method.save_to_db()
    return redirect(url_for("library.manage_db"))


@library_blueprint.route('/add_algorithm', methods=['POST'])
def add_algorithm():
    algorithm_type = request.form['algorithm_type']
    algorithm_preprocessors = request.form['algorithm_preprocessors']
    algorithm_issues = request.form['algorithm_issues']
    new_algorithm = AlgorithmModel(algorithm_type=algorithm_type, algorithm_preprocessors=algorithm_preprocessors,
                                   algorithm_issues=algorithm_issues)
    new_algorithm.save_to_db()
    return redirect(url_for("library.manage_db"))

_Dockerized/mldashboard/web/project/library/templates/add_request.html
{% extends 'base.html' %} {% block content %}


<div class="row">
    <div class="col-md-4 text-left">
        <form action="{{url_for('library.new_code') }}" method="POST" id="new_code" enctype="multipart/form-data" class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h3>Add Template:</h3>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12" >
                        <i class="material-icons prefix">assignment</i>
                        <input id="name" name="name" type="text" class="validate" required>
                        <label for="icon_prefix">Choose a name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="dropdown" name="type_dropdown">
                        <i class="material-icons prefix">storage</i>
                        <select id="type_of_algorithm" name="type_of_algorithm">
                          <option value="" disabled selected>Choose type:</option>
                          {% for type in types %}
                            <option value={{type.type_of_algorithm}}>{{type.type_of_algorithm}}</option>
                          {% endfor %}
                        </select>
                        <label>Type of Algorithm</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="dropdown"  name="complexity_dropdown">
                        <i class="material-icons prefix">storage</i>
                        <select id="complexity" name="complexity">
                  <option value="" disabled selected>Choose type:</option>
                  {% for grade in complexities %}
                      <option value={{grade.complexity}}>{{grade.complexity}}</option>
                  {% endfor %}
                </select>
                        <label>Complexity</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="dropdown"  name="method_dropdown">
                        <i class="material-icons prefix">storage</i>
                        <select id="method" name="method">
                  <option value="" disabled selected>Choose method:</option>
                  {% for met in methods %}
                      <option value={{met.method}}>{{met.method}}</option>
                  {% endfor %}
                </select>
                        <label>Learning Method</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">assignment</i>
                        <input id="author" name="author" type="text" class="validate" required>
                        <label for="icon_prefix">Author</label>
                    </div>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12" id="python_file">
                        <div class="col-md-4 text-left no-padding-left">
                            <span><i class="material-icons prefix" style="display:inline; top:0.1rem;">storage</i>
                            <h3 style="margin-left: 30px; display:inline; backgroud-color: grey;">Add .py file:</h3></span>
                        </div>
                        <div class="col-md-1 text-left">
                            <input type="file" name="inputFile">
                        </div>
                    </div>
                    <div class="row"></div>
                     <div class="row"></div>
                    <div class="row">
                        <div class="col-md-4 text-center"></div>
                        <div class="col-md-4 text-center no-padding-left">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="navigation">ADD TEMPLATE</button>
                        </div>
                        <div class="col-md-4 text-center"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
        $(document).ready(function() {
            $('select').formSelect();
        });
    </script>

{% endblock %}

_Dockerized/mldashboard/web/project/library/templates/edit_code.html
{% extends 'base.html' %} {% block content %}

<div class="row">
    <div class="col-md-6 text-left">
        <form action="{{url_for('library.update_code', code_id=code.id) }}" method="POST" enctype="multipart/form-data" id="edit_code" class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h3>Edit Template:</h3>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">assignment</i>
                        <input id="name" name="name" type="text" class="validate" value="{{code.name}}">
                        <label id="field_label" for="icon_prefix">Model</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">storage</i>
                        <select id="type_of_algorithm" name="type_of_algorithm">
                  <option value="" disabled selected>Choose Type</option>
                  {% for type in types %}
                      {% if type.type_of_algorithm == code.type_of_algorithm%}
                      <option value="{{type.type_of_algorithm}}" selected >{{type.type_of_algorithm}}</option>
                      {% else %}
                       <option value="{{type.type_of_algorithm}}">{{type.type_of_algorithm}}</option>
                    {% endif %}
                  {% endfor %}
                </select>
                        <label>Type of Algorithm</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">storage</i>
                        <select id="complexity" name="complexity">
                  <option value="" disabled selected>Choose Type</option>
                  {% for grade in complexities %}
                      {% if grade.complexity == code.complexity%}
                      <option value="{{grade.complexity}}" selected >{{grade.complexity}}</option>
                      {% else %}
                       <option value="{{grade.complexity}}">{{grade.complexity}}</option>
                    {% endif %}
                  {% endfor %}
                </select>
                        <label>Complexity</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">storage</i>
                        <select id="method" name="method">
                  <option value="" disabled selected>Choose Method</option>
                  {% for met in methods %}
                      {% if met.method == code.method%}
                      <option value="{{code.method}}" selected >{{met.method}}</option>
                      {% else %}
                       <option value="{{met.method}}">{{met.method}}</option>
                    {% endif %}
                  {% endfor %}
                </select>
                        <label>Learning Method</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">assignment</i>
                        <input id="author" name="author" type="text" class="validate" value="{{code.author}}">
                        <label id="field_label" for="icon_prefix">Author</label>
                    </div>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12">
                        <div class="col-md-3 text-left" style="margin-left: -15px">
                            <span><i class="material-icons prefix" style="display:inline; top:0.1rem;">storage</i>
                            <h3 style="margin-left: 30px; display:inline; backgroud-color: grey;">Add .py file:</h3>
                        </div>
                        <div class="col-md-1 text-left">
                            <input type="file" name="inputFile">
                        </div>
                    </div>
                    <div class="row"></div>
                    <div class="row"></div>
                                        <div class="row">
                        <div class="col-md-4 text-center"></div>
                        <div class="col-md-4 text-center no-padding-left">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="navigation">SAVE CHANGES</button>
                        </div>
                        <div class="col-md-4 text-center"></div>
                    </div>
                </div>
        </form>
        </div>
    </div>
</div>
</div>
<script>
        $(document).ready(function() {
            $('select').formSelect();
        });
</script>


{% endblock %}

_Dockerized/mldashboard/web/project/library/templates/error.html
{% extends 'base.html' %} {% block content %}

<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>
<div class="row"></div>

<div class="row">
    <div class="col-md-4 text-center"></div>
    <div class="col-md-4 text-center">
        <div class="card" id="title_card">
            <div class="row">
                <h2>Please fill out all required fields and make sure that uploaded file is *.py</h2>
            </div>
            <div class="row">
                <div class="col-md-3 text-center"></div>
                <div class="col-md-6 text-center">
                <a href="{{url_for('library.library')}}"  onclick="goBack()" class="waves-effect waves-light btn-large" id="navigation"><i class="large material-icons left">keyboard_return</i>Back to Template</a>
                </div>
                <div class="col-md-3 text-center"></div>
        </div>
    </div>
    <div class="col-md-4 text-center"></div>
</div>

{% endblock %}

_Dockerized/mldashboard/web/project/library/templates/library.html
{% extends 'base.html' %} {% block content %}


<div class="row"></div>
<div class="col-md-12 col-lg-9 text-center">
    <div class="card" id="title_card">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-3 text-left">
                <div class="row">
                    <h3>Available Code Templates:</h3>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-5 text-center">
            </div>
            <div class="col-sm-12 col-md-12 col-lg-4 text-left">
                <div class="row">
                    <div class="col-xs-6  col-sm-2  col-md-2 text-left">
                        <h3>Contribute:</h3>
                    </div>
                    <div class="col-md-0 col-lg-2 text-center">
                    </div>
                    <div class="col-xs-6  col-sm-6 col-md-6 col-lg-4 text-left">
                        <a href="{{url_for('library.add_request')}}" class="waves-effect waves-light btn btn_small btn-add_template" id="navigation">ADD TEMPLATE</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-left">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered" id="dataTables-example">
                        <thead>
                            <tr>
                                <th class="center">Model Name</th>
                                <th class="center">Type of Estimator</th>
                                <th class="center">Complexity</th>
                                <th class="center">Learning Method</th>
                                <th class="center">Author</th>
                                <th class="center">Edit</th>
                                <th class="center">Delete</th>
                                <th class="center">Download</th>
                                <th class="center">Downloads</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in codes%}
                            <tr class="odd gradeA">
                                <td class="center">{{data.name}}</td>
                                <td class="center"><a href="{{url_for('algorithms.summary', type_id = data.type_of_algorithm)}}" class="waves-effect waves-light btn btn_table">{{data.type_of_algorithm}}</a></td>
                                <td class="center">{{data.complexity}}</td>
                                <td class="center">{{data.method}}</td>
                                <td class="center">{{data.author}}</td>

                                <td class="center">
                                    <a href="{{url_for('library.edit_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_table" >Edit</a>
                                </td>
                                <td class="center">
                                    <a href="{{url_for('library.delete_code', code_id=data.id)}}" class="waves-effect waves-light btn btn_table">Delete</a>
                                </td>
                                <td class="center">
                                    <form action="{{url_for('library.download_code', code_id=data.id) }}" method="GET" enctype="multipart/form-data">
                                        <button type="Download" class="btn btn_table">Download</button>
                                    </form>
                                </td>
                                <td class="center">{{data.downloads}}</td>
                            </tr>

                            {% endfor%}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-12 col-md-12 col-lg-3 text-center">
    <div class="row">
        <div class="card text-left" id="extra_card">
            <div class="row">
                <h3>Types of Estimator:</h3>
            </div>
            {% for type in types%}
            <a href="{{url_for('algorithms.summary', type_id=type.type_of_algorithm)}}" class="waves-effect waves-light btn btn_small" id="navigation">{{type.type_of_algorithm}}</a>
            <div class="row">
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="card" id="extra_card">
            <div class="row text-left">
                <h3>Check other projects:</h3>
            </div>
            <div class="row text-left">
                <input type="text" id="gh-username" value="LukaszMalucha" oninput="fetchGitHubInformation()" />
            </div>
            <div class="row">
                <div id="repo_content">
                    <div id="gh-repo-data"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable();
        });
    </script>
{% endblock %}

_Dockerized/mldashboard/web/project/library/templates/manage_db.html
{% extends 'base.html' %} {% block content %}


<div class="row">
    <div class="col-md-1 text-left"></div>
    <div class="col-md-3 text-left" style="margin-right: 50px">
        <form action="{{url_for('library.add_algorithm_type') }}" method="POST" enctype="multipart/form-data" id="add_algorithm_type_form" class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h4 id = "db_fill">Add Algorithm Type:</h4>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="type" name="type" type="text" class="validate" required>
                        <label for="icon_prefix">Type</label>
                    </div>
                </div>
                <div class="row">
                    <div class="row">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="type">ADD</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3 text-left" style="margin-right: 50px">
        <form action="{{url_for('library.add_complexity') }}" method="POST" id="add_complexity_form" class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h4 id = "db_fill">Add Complexity:</h4>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="complexity" name="complexity" type="text" class="validate" required>
                        <label for="icon_prefix">Complexity</label>
                    </div>
                </div>

                <div class="row">
                    <div class="row">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="complexity">ADD</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-3 text-left" style="margin-right: 50px">
        <form action="{{url_for('library.add_method') }}" method="POST" enctype="multipart/form-data" id="add_method_form" class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h4 id = "db_fill">Add Method:</h4>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="method" name="method" type="text" class="validate" required>
                        <label for="icon_prefix">Method</label>
                    </div>
                </div>
                <div class="row">
                    <div class="row">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="method">ADD</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
</div>
<div class="row">
    <div class="col-md-1 text-left"></div>

<div class="col-md-3 text-left" style="margin-right: 50px">
        <form action="{{url_for('library.add_algorithm') }}" method="POST" id="add_algorithm_form"class="col s12">
            <div class="card" id="title_card">
                <div class="col-md-6 text-left">
                    <h4 id = "db_fill">Add Algorithm:</h4>
                </div>
                <div class="row"></div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="algorithm_type" name="algorithm_type" type="text" class="validate" required>
                        <label for="icon_prefix">AlgoType</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="algorithm_preprocessors" name="algorithm_preprocessors" type="text" class="validate" required>
                        <label for="icon_prefix">Preprocessers</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12" id="field">
                        <i class="material-icons prefix">assignment</i>
                        <input id="algorithm_issues" name="algorithm_issues" type="text" class="validate" required>
                        <label for="icon_prefix">Issues</label>
                    </div>
                </div>
                <div class="row">
                    <div class="row">
                        <button class="btn waves-effect waves-light" type="submit" name="action" id="algo">ADD</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}