_Dockerized/mldashboard/web/project/users/views.py
from flask import render_template, redirect, url_for, Blueprint, session
from werkzeug.security import generate_password_hash, check_password_hash

users_blueprint = Blueprint(
    'users', __name__,
    template_folder="templates"
)

from .forms import *
from .models import UserModel


########################################################################## USER VIEWS ###################################################################################################################


## SIGN UP ##########################################################################

@users_blueprint.route('/signup', methods=["GET", "POST"])
def signup():
    form = RegisterForm()
    session['current_user'] = 'Guest'
    if form.validate_on_submit():
        if UserModel.find_by_username(form.username.data) or UserModel.find_by_email(form.email.data):
            return render_template('signup.html', form=form, message="User already exists")

        hashed_password = generate_password_hash(form.password.data,
                                                 method='sha256')  ## password get hashed for security purposes
        new_user = UserModel(username=form.username.data, email=form.email.data, password=hashed_password)
        new_user.save_to_db()
        return redirect(url_for('users.login'))

    return render_template('signup.html', form=form)  ## passing signup form to signup template


## LOGIN ############################################################################

@users_blueprint.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():  ## if form was submitted....
        user = UserModel.find_by_username(username=form.username.data)
        if user:
            if check_password_hash(user.password, form.password.data):
                session['current_user'] = user.username
                return redirect(url_for('library.library'))

        return render_template('login.html', form=form, message="Invalid Username or Password")

    return render_template('login.html', form=form)  ## passing login form to login template


## LOGOUT ###########################################################################

@users_blueprint.route('/logout')
def logout():
    session['current_user'] = 'Guest'
    return redirect(url_for('users.login'))

_Dockerized/mldashboard/web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ML Dashboard</title>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- FontAwesome Styles-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" crossorigin="anonymous"></script>
    <!-- Google Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- Custom Styles-->
    <link href="{{url_for('static', filename='css/custom-styles.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='css/navbar.css')}}" rel="stylesheet" />
     <!-- jQuery Js -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Materialize Js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- Data Tables -->

    <script src="{{url_for('static', filename='js/dataTables/jquery.dataTables.js')}}"></script>
    <script src="{{url_for('static', filename='js/dataTables/dataTables.bootstrap.js')}}"></script>

</head>



<body>
    <!-- WRAPPER -->
    <div id="wrapper">




        <!-- TOP NAVBAR -->
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand waves-effect waves-dark" href="{{ url_for('library.library')}}"><i class="material-icons">blur_on</i><strong>ML Dashboard</strong></a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li><a class="nav-link" target="_blank" href="https://www.linkedin.com/in/lukaszmalucha/"><i class="fab fa-linkedin"></i><b> LinkedIn</b></a></li>
                <li><a class="nav-link" target="_blank" href="https://lukaszmalucha.github.io/portfolio/"><i class="fab fa-github"></i> <b> GitHub</b></a></li>
                <li><a class='dropdown-trigger nav-link' href='#' data-target='dropdown1' id="user_dropdown"><i class="fas fa-caret-down"></i><b> {{ current_user }}</b></a></li>
                <li><a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons" id="trigger">menu</i></a></li>
            </ul>
        </nav>

        <!-- DROPDOWN -->
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="{{ url_for('users.login') }}" id="login"><i class="fa fa-user fa-fw"></i><b> Log In</b></a>
            </li>
            <li><a href="{{ url_for('users.logout') }}" id="navigation"><i class="fas fa-sign-out-alt"></i><b> Log Out</b></a>
            </li>
            <li><a href="{{ url_for('users.signup') }}" id="navigation"><i class="fas fa-tasks"></i><b> Sign In</b></a>
            </li>
            <li><a href="{{ url_for('library.manage_db') }}" id="dropdown_link"><i class="fas fa-cog"></i>Manage DB</a>
            </li>
        </ul>

        <!-- MOBILE -->
        <ul class="sidenav" id="mobile-demo">
            <li><a href="{{ url_for('users.login') }}" id="login"><i class="fa fa-user fa-fw"></i><b> Log In</b></a>
            </li>
            <li><a href="{{ url_for('users.logout') }}" id="navigation"><i class="fas fa-sign-out-alt"></i><b> Log Out</b></a>
            </li>
            <li><a href="{{ url_for('users.signup') }}" id="navigation"><i class="fas fa-tasks"></i><b> Sign In</b></a>
            </li>
            <li><a href="{{ url_for('library.manage_db') }}" id="dropdown_link"><i class="fas fa-cog"></i>Manage DB</a>
            </li>
        </ul>
        


        <!--/. TOP NAVBAR ****************************************************************************************************************************************************************************************** -->

            <!-- PAGE-INDEX -->
            <div id="page-index">
                <div class="dashboard-cards">
                    {% block content %} {% endblock %}

                </div>

            </div>
            <!-- PAGE-INDEX -->

        </div>
        
        <!-- PAGE-WRAPPER -->

    </div>
    <!-- WRAPPER -->
    <script>
        $('.dropdown-trigger').dropdown();
    </script>
    <!-- Bootstrap Js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
    <!-- jQueryGitHub -->
    <script src="{{url_for('static', filename='js/github-information.js')}}"></script>
    <script>
        $(document).ready(function() {
            $('.sidenav').sidenav();
        });
    </script>




</body>

</html>